# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking

# It's not necessary to copy all keys to your config.
# If the key is missing in your config, "default-config.toml" will serve as a fallback

# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 8

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       5
outer.bottom =     5
outer.top =        5
outer.right =      5

# Bindings modes
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes

[mode.disable.binding]
# This mode doesn't have any bindings. This is useful as a escape hatch to reuse binding in other apps.
esc = 'mode main'
space = 'mode main'

# 'main' binding mode declaration
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# You can uncomment this line to open up terminal with alt + enter shortcut
# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-shift-h = 'focus left'
ctrl-shift-j = 'focus down'
ctrl-shift-k = 'focus up'
ctrl-shift-l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -100'
alt-shift-equal = 'resize smart +100'

alt-shift-f = 'fullscreen'
alt-shift-t = 'layout floating tiling' # Toggle between floating and tiling layout
ctrl-shift-slash = 'layout horizontal vertical'
alt-shift-slash = 'layout horizontal vertical'
ctrl-shift-quote = 'layout tiles accordion'
alt-shift-quote = 'layout tiles accordion'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-shift-period = 'workspace next'
ctrl-shift-comma = 'workspace prev'
ctrl-shift-backtick = 'workspace-back-and-forth'
ctrl-shift-backslash = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-backslash = 'move-workspace-to-monitor --wrap-around next'

# In your config, you can drop workspace bindings that you don't need
ctrl-shift-1 = 'workspace 1'
ctrl-shift-p = 'workspace 1' 
ctrl-shift-2 = 'workspace 2'
ctrl-shift-o = 'workspace 2'
ctrl-shift-3 = 'workspace 3'
ctrl-shift-i = 'workspace 3'
ctrl-shift-4 = 'workspace 4'
ctrl-shift-u = 'workspace 4'
ctrl-shift-5 = 'workspace 5'
ctrl-shift-y = 'workspace 5'
ctrl-shift-6 = 'workspace 6'
ctrl-shift-7 = 'workspace 7'
ctrl-shift-8 = 'workspace 8'
ctrl-shift-9 = 'workspace 9'
ctrl-shift-0 = 'workspace 10'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-p = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-o = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-i = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-u = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-y = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']
alt-shift-0 = ['move-node-to-workspace 10', 'workspace 10']

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
ctrl-space = 'mode service'
ctrl-backspace = 'mode disable'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
space = ['reload-config', 'mode main']
ctrl-backspace = 'mode disable'

s = ['flatten-workspace-tree'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#t = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
#backspace = ['close-all-windows-but-current', 'mode main']
slash = 'layout horizontal vertical'
quote = 'layout tiles accordion'
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
tab = 'workspace-back-and-forth'
backslash = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-backslash = 'move-workspace-to-monitor --wrap-around next'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
h = 'focus left'
j = 'focus down'
k = 'focus up'
l = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
shift-h = 'move left'
shift-j = 'move down'
shift-k = 'move up'
shift-l = 'move right'

alt-shift-h = ['join-with left']
alt-shift-j = ['join-with down']
alt-shift-k = ['join-with up']
alt-shift-l = ['join-with right']

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
minus = 'resize smart -50'
equal = 'resize smart +50'
shift-minus = 'resize smart -200'
shift-equal = 'resize smart +200'

f = 'fullscreen'
t = ['layout floating tiling', 'move-mouse window-force-center'] # Toggle between floating and tiling layout
g = ['layout floating tiling', 'move-mouse window-force-center'] # Toggle between floating and tiling layout

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
period = 'workspace next'
comma = 'workspace prev'

# In your config, you can drop workspace bindings that you don't need
1 = 'workspace 1'
p = 'workspace 1'
2 = 'workspace 2'
o = 'workspace 2'
3 = 'workspace 3'
i = 'workspace 3'
4 = 'workspace 4'
u = 'workspace 4'
5 = 'workspace 5'
y = 'workspace 5'
6 = 'workspace 6'
7 = 'workspace 7'
8 = 'workspace 8'
9 = 'workspace 9'
0 = 'workspace 10'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
shift-1 = ['move-node-to-workspace 1', 'workspace 1']
shift-p = ['move-node-to-workspace 1', 'workspace 1']
shift-2 = ['move-node-to-workspace 2', 'workspace 2']
shift-o = ['move-node-to-workspace 2', 'workspace 2']
shift-3 = ['move-node-to-workspace 3', 'workspace 3']
shift-i = ['move-node-to-workspace 3', 'workspace 3']
shift-4 = ['move-node-to-workspace 4', 'workspace 4']
shift-u = ['move-node-to-workspace 4', 'workspace 4']
shift-5 = ['move-node-to-workspace 5', 'workspace 5']
shift-y = ['move-node-to-workspace 5', 'workspace 5']
shift-6 = ['move-node-to-workspace 6', 'workspace 6']
shift-7 = ['move-node-to-workspace 7', 'workspace 7']
shift-8 = ['move-node-to-workspace 8', 'workspace 8']
shift-9 = ['move-node-to-workspace 9', 'workspace 9']
shift-0 = ['move-node-to-workspace 10', 'workspace 10']

# See: https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback
# Run `aerospace --list-apps` to get the list of all running apps
[[on-window-detected]]
if.app-name-regex-substring = 'scrcpy|Firefox|finance'
run = 'move-node-to-workspace 1' # P

[[on-window-detected]]
if.app-name-regex-substring = 'Chrome'
run = 'move-node-to-workspace 2' # O

[[on-window-detected]]
if.app-name-regex-substring = 'Android Studio|Intellij|iTerm'
run = 'move-node-to-workspace 3' # I

[[on-window-detected]]
if.app-name-regex-substring = 'gMail|Slack'
run = 'move-node-to-workspace 4' # 4

[[on-window-detected]]
if.app-name-regex-substring = 'Music'
run = 'move-node-to-workspace 5' # Y

[[on-window-detected]]
if.app-name-regex-substring = 'Calendar'
run = 'move-node-to-workspace 7'

[[on-window-detected]]
if.app-name-regex-substring = 'Moonlight'
run = 'move-node-to-workspace 8'

[[on-window-detected]]
if.app-name-regex-substring = 'KeepassXC'
run = 'move-node-to-workspace 9'

