# shellcheck shell=bash
platform mac linux
module "Midnight Commander — file manager"

# ~/.config/mc is a real directory: static config is symlinked back to
# this repo, generated and runtime files are local copies.  It used to
# be a symlink to this directory, which meant MC wrote its runtime state
# (ini, panels.ini) straight into the working tree, and setup rewrote
# the tracked mc.ext.ini with an absolute path recording whichever
# machine last ran it.  `link` replaces that stale symlink on its own.
link handlers.ini ~/.config/mc/handlers.ini \
  "File-type handlers — which command opens which type"
link open-file.sh ~/.config/mc/open-file.sh \
  "Cross-platform open helper"
link mc.keymap ~/.config/mc/mc.keymap \
  "Keybindings"

# ini and mc.ext.ini are seeded and generated by install.sh.
